name: CI to Docker Hub

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DHI (Docker Hardened Image)
        uses: docker/login-action@v4
        with:
          registry: dhi.io
          username: apentsak
          password: ${{ secrets.DHI_TOKEN }}

      - name: DHI Pull
        run: docker pull dhi.io/gradle:8-jdk17-debian-dev

      - name: Verify AWS CLI version
        run: aws --version

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build BASE
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile_new
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: ${{ secrets.DOCKER_HUB_ORGANIZATION_NAME }}/ci-cd:base
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build Runner
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: ${{ secrets.DOCKER_HUB_ORGANIZATION_NAME }}/ci-cd:runner
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image SCOUT CVES
        run: |
          docker scout cves ${{ secrets.DOCKER_HUB_ORGANIZATION_NAME }}/ci-cd:base
          docker scout cves ${{ secrets.DOCKER_HUB_ORGANIZATION_NAME }}/ci-cd:runner
